demos:
  display_name: "Demos"
  description: "Install demos of content in your site."
  options:
    non_demo:
      title: "- None -"
      description: "No demo"
      source_name: ""
    small:
      title: "Small Company"
      description: "Example for a small company demo"
      source_name: "cucumber_demo_small"
    medium:
      title: "Medium Company"
      description: 'Example for a medium company demo'
      source_name: "cucumber_demo_medium"
    large:
      title: "Large Company"
      description: 'Example for a large company demo'
      source_name: "cucumber_demo_large"
