recipes:
  display_name: "Recipes"
  description: "Install recipes of works in your site."
  options:
    products:
      title: "Products"
      description: "Products testing management"
      source_name: "cucumber_products"
      selected: true
    componentes:
      title: "Components"
      description: 'Components testing management'
      source_name: "cucumber_components"
      selected: true
    projects:
      title: "Projects"
      description: 'Projects testing management'
      source_name: "cucumber_projects"
      selected: true