user_roles:
  display_name: "User Roles"
  description: "Install user roles that have separate permissions based on the role rank and the roles can be modified later."
  options:
    tester:
      title: "Tester"
      description: "The role of the tester is to write features for projects, products, and components, implement testing, and ensure that all testing is done correctly."
      source_config: "cucumber_user_role_tester"
      selected: false
      disabled: false
    developer:
      title: "Developer"
      description: "Write and perform productive code, keep and update existing rules."
      source_config: "cucumber_user_role_developer"
      selected: false
      disabled: false
    designer:
      title: "Designer"
      description: "Analyse research findings to inform design directions. Evaluate new design ideas or concepts. Provide on-the-job training to direct reports and junior team "
      source_config: "cucumber_user_role_designer"
      selected: false
      disabled: false
    analyst:
      title: "Analyst"
      description: "Analyse the defects and bugs to identify what is causing them, keep software and systems documentation up to date."
      source_config: "cucumber_user_role_analyst"
      selected: false
      disabled: false
    coordinator:
      title: "Coordinator"
      description: "Day-to-day coordination of test activities, Executing work distribution, Establishing plans, Monitoring progress."
      source_config: "cucumber_user_role_coordinator"
      selected: false
      disabled: false
    product_owner:
      title: "Product Owner"
      description: "Managing the product backlog and prioritizing them based on changing requirements. Overseeing all stages of product creation including design and development."
      source_config: "cucumber_user_role_product_owner"
      selected: false
      disabled: false
    admin:
      title: "Admin"
      description: "System manager"
      source_config: "cucumber_user_role_admin"
      selected: true
      disabled: true