install-page:
  css:
    theme:
      css/theme/install-page.css: { }
  dependencies:
    - system/maintenance
    - claro/install-page

toolbar-icon:
  css:
    theme:
      css/theme/admin-toolbar-tools.css: { }
