<?php

/**
 * @file
 * Set up variables to be placed within the template (.html.twig) files.
 *
 * The variables set up here apply to both templates (.html.twig) files and
 * functions (theme_HOOK). These are also used for providing
 * @link https://www.drupal.org/node/2354645 Twig Template naming conventions @endlink.
 *
 * @see process.inc
 */

/**
 * Implements template_preprocess_page().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_page(&$variables) {
}
// */

/**
 * Implements template_preprocess_block().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_block(&$variables) {
}
// */

/**
 * Implements template_preprocess_breadcrumb().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_breadcrumb(&$variables) {
}
// */

/**
 * Implements template_preprocess_details().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_details(&$variables) {
}
// */

/**
 * Implements hook_preprocess_HOOK() for feed-icon.html.twig.
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_feed_icon(&$variables) {
}
// */

/**
 * Implements template_preprocess_form_element().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_form_element(&$variables) {
}
// */

/**
 * Implements template_preprocess_form_element() for form-element--advanced.html.twig.
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_form_element__advanced(&$variables) {
}
// */

/**
 * Implements template_preprocess_links() for links--dropbutton.html.twig.
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_links__dropbutton(&$variables) {
}
// */

/**
 * Implements template_preprocess_menu_local_action().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_menu_local_action(&$variables) {
}
// */

/**
 * Implements hook_preprocess_HOOK() for menu-local-tasks.html.twig.
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_menu_local_tasks(&$variables) {
}
// */

/**
 * Implements hook_preprocess_HOOK() for menu--navbar.html.twig
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_menu__navbar(&$variables) {
}
// */

/**
 * Implements hook_preprocess_HOOK() for menu--offcanvas.html.twig
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_preprocess_menu__offcanvas(&$variables) {
}
// */
