<?php

/**
 * @file
 * Set up variables to be placed within the template (.html.twig) files.
 *
 * The variables set up here apply to both templates (.html.twig) files and
 * functions (theme_HOOK). See preprocess.inc for providing
 * @link https://www.drupal.org/node/2354645 Twig Template naming conventions @endlink.
 *
 * @see preprocess.inc
 */

/**
 * Implements template_process_page().
 */
/* -- Delete this line if you want to use this function
function cucumber_frontend_process_page(&$variables) {
}
// */
